### ISSUE TITLE
Avoid duplicate generated types

### ISSUE THREAD

**Issue by vitorcamachoo** [croutonn/graphql-codegen-plugin-typescript-swr#121]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ X] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Hii, 
I want to know if theres any chance of reusing some generated types file instead bundling the generated types into the generated request file. For example, I have the following configuration:
```yaml
libs/backoffice/api/graphql/yacooba/types.ts:
    schema: "https://dev-api.yacooba.live/graphql"
    plugins:
      - typescript
    config:
      skipTypename: true

libs/backoffice/api/graphql/yacooba/request.ts:
    schema: "https://dev-api.yacooba.live/graphql"
    documents:
      - 'apps/**/*.yacooba.graphql'
      - 'libs/**/*.yacooba.graphql'
    plugins:
      - typescript
      - typescript-operations
      - typescript-graphql-request
      - plugin-typescript-swr
    config:
      autogenSWRKey: true
      skipTypename: true
      useTypeImports: true
      dedupeOperationSuffix: true
```

The result will have types duplicated, one in `types.ts` file and the other will be bundled into request file interfaces `request.ts`. How can I avoid this duplication maintaining these two files ?
