### ISSUE TITLE
TypeError: visitFn.call is not a function

### ISSUE THREAD

**Issue by danestves** [croutonn/graphql-codegen-plugin-typescript-swr#179]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

When running the `generate` from `graphql-codegen` i recieve the following error:

```bash
✖ src/generated/graphql.ts
    TypeError: visitFn.call is not a function
        at visit (/Users/danestves/seeed/blendi/app/node_modules/graphql/language/visitor.js:200:21)
        at Object.plugin (/Users/danestves/seeed/blendi/app/node_modules/graphql-codegen-plugin-type
script-swr/build/main/index.js:21:25)
```

This is my schema:
```yml
overwrite: true
schema: ${API_URL}/graphql
documents: 'src/**/*.graphql'
generates:
  src/generated/graphql.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      # Put `plugin-typescript-swr` below `typescript-graphql-request`
      - 'typescript-graphql-request'
      - 'plugin-typescript-swr'
    config:
      rawRequest: false
      autogenSWRKey: true
```

These are my dependency versions:

```
"graphql": "^16.0.1",
"graphql-request": "^3.6.1",
"swr": "^1.0.1",
"@graphql-codegen/cli": "2.2.2",
"@graphql-codegen/typescript": "2.3.1",
"@graphql-codegen/typescript-graphql-request": "^4.3.0",
"@graphql-codegen/typescript-operations": "2.2.0",
"graphql-codegen-plugin-typescript-swr": "^0.7.0",
```

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
