### ISSUE TITLE
Can't get generator to work properly

### ISSUE THREAD

**Issue by baboons** [croutonn/graphql-codegen-plugin-typescript-swr#3]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ x] question about how to use this project

- **Summary**
I'm trying to get the SWR hooks to be generated but the SDK is lacking those. Not sure what I'm doing wrong?

- **Other information** 
graphql.ts
```
export type SdkFunctionWrapper = <T>(action: () => Promise<T>) => Promise<T>;

const defaultWrapper: SdkFunctionWrapper = (sdkFunction) => sdkFunction();
export function getSdk(
  client: GraphQLClient,
  withWrapper: SdkFunctionWrapper = defaultWrapper
) {
  return {};
}
export type Sdk = ReturnType<typeof getSdk>;
export type SWRInfiniteKeyLoader<Data = any> = (
  index: number,
  previousPageData: Data | null
) => string | any[] | null;
export function getSdkWithHooks(
  client: GraphQLClient,
  withWrapper: SdkFunctionWrapper = defaultWrapper
) {
  const sdk = getSdk(client, withWrapper);
  return {
    ...sdk,
  };
}
export type SdkWithHooks = ReturnType<typeof getSdkWithHooks>;
```

my config
```
overwrite: true
schema:
  - https://graphql.fauna.com/graphql:
      headers:
        Authorization: "xxx"
generates:
  src/generated/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-graphql-request"
      - "plugin-typescript-swr"
  ./graphql.schema.json:
    plugins:
      - "introspection"
config:
  rawRequest: true
  useSWRInfinite:
    - allQuestions
```
